# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Cultivating Young Minds
email: daisypheme@gmail.com
author: Mahlatse Makalancheche
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2016 Cultivating Young Minds. All Rights Reserved.'
credits: 'Credits: Theme by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

#-------------------------#
#     Site Navigation     #
#-------------------------#
navigation:
  - title: Home
    link: home
  - title: Services
    link: services
  - title: About
    link: about
  - title: Contact
    link: contact

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com
  - title: linkedin
    url: https://www.linkedin.com
